network:
  version: 2
  renderer: networkd
  ethernets:
    ens192:
      #link-local: [ipv4]
      dhcp4: no
      dhcp6: no
      addresses: [10.10.10.47/24]
      routes:
        - to: default
          via: 10.10.10.254
      nameservers:
        search: [pantel.local, pantel.internal]
        addresses: [10.10.10.100]